# Generated by Django 4.1.5 on 2023-01-10 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameA', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameF', models.CharField(max_length=150)),
                ('legs', models.IntegerField(default=2)),
                ('weight', models.IntegerField(default=55)),
                ('height', models.IntegerField(default=65)),
                ('speed', models.IntegerField(default=78)),
                ('family_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.family')),
            ],
        ),
    ]
